### ISSUE TITLE
OpenGL hui

### ISSUE THREAD

**Issue by joeblew99** [cpmech/gosl#11]
I am a building architect working on energy , 3d printing and medical systems.

Me and a few others are building a OpenGL based GUI toolkit .

It replaces lots of stuff your using.

https://github.com/cpmech/gosl/blob/master/plt/README.md

We are used to use Qt and other tools and decided we had enough :)

I am from Melbourne but live in Berlin now.

I would love to use your code as a basis to check our OpenGL Toolkit written in golang can fulfil the needs that you have and get you involved in dog fooding our framework too.

Our device targets are all desktops, mobiles, web ( via webgl and gopherjs).
Our GUI targets:
Forms, 2d canvas surfaces for stuff like flow diagrams.
3d for 3d models and for computation using Vulkan.
Vulkan Run in all device targets btw.

If you interested I will shoot you a link.

**Comment by cpmech** [comment]
Not at the moment. Cheers.
