### ISSUE TITLE
Example problem?

### ISSUE THREAD

**Issue by davmaz** [cpmech/gosl#19]
Great package! I was trying the examples and got the following error. Am I missing something?
>>> running vtk_isosurf01.go <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
# github.com/cpmech/gosl/vtk
In file included from connectgovtk.cpp:10:0:
clrmap.h:12:28: fatal error: vtkLookupTable.h: No such file or directory
compilation terminated.

**Comment by cpmech** [comment]
Thanks.

To compile the VTK package, please run
`xgenflagsfile.bash`
and
`go install`
inside the gosl/vtk directory

Please note that this was tested on Ubuntu 16.04 and may not work on later versions unless the VTK_VERSION in xgenflagsfile.bash is fixed.

I'm still trying to get `pkgconfig` to work here...

**Comment by davmaz** [comment]
Yes, that fixed the problem. Your work is really helpful and it's a great package. All the examples you have sell it well.

I wonder if the gonum group knows about your package. There's is similar, but it doesn't have as many examples and support for the vast range of problems yours does.

I'm definitely following your github and if you ever need someone to test things don't hesitate to let me know. My math background is nowhere near yours so I can't help with development.

Overall it's great work, and the go community benefits significantly!

________________________________

**Comment by cpmech** [comment]
Cheers, mate!
