### ISSUE TITLE
2d interpolation (bicubic/bilinear)

### ISSUE THREAD

**Issue by cbuesser** [cpmech/gosl#23]
Hi,
I'm interested in implementing something, similar to DataInterp, to be used with two-dimensional discrete data interpolation.

I was thinking that an interface similar to [alglib's 2dinterpolation](http://www.alglib.net/translator/man/manual.cpp.html#unit_spline2d) would work?

Is this something you would want in this library?

**Comment by cpmech** [comment]
Hi, it sounds like a good addition. Maybe as a sub-package fun/spline. PRs are very welcome :-)

**Comment by cpmech** [comment]
Thanks again. I've added your name to AUTHORS if you won't mind.

You may like to check [t_multiinterp_test.go](https://github.com/cpmech/gosl/blob/master/fun/t_multiinterp_test.go) to see the resulting plot. Also, there is a function `verbose()` that I like to enable/disable (using comments) while I'm writing the test.

![multiinterp01](https://user-images.githubusercontent.com/9506388/38158961-5581cae2-3453-11e8-9336-a2134c6a0c14.png)
