### ISSUE TITLE
gcc version is hardcoded?

### ISSUE THREAD

**Issue by sbromberger** [cpmech/gosl#26]
Hi,

It's not a huge deal, but I noticed that for Darwin, the gcc version is hard-coded in 
https://github.com/cpmech/gosl/blob/840c88707193892f069608d0ca5afa8662cb9aba/num/qpck/flags.go#L12

The current version of gcc installed via homebrew is 8.1.0. How difficult would it be to change this to be more dynamic?

**Comment by cpmech** [comment]
Hi, sorry for the delay.

I've tried to improve this but it seems impossible.

The problem is that HomeBrew does not install GCC in a standard location (e.g. `/usr/local/lib`). Only with a script or a manual creation of a linked directory would fix this.

Thanks for the suggestion, nevertheless.

**Comment by cpmech** [comment]
All right! I think I've fixed this inconvenience.

My `all.bash` script should now autodetect the GCC version on macOS.

See changes here: https://github.com/cpmech/gosl/commit/c34297e62614b37a77d9a492fb7386f44e35fdb9

NOTE: I've tested with the most recent HomeBrew packages. The installation procedure from the user perspective hasn't changed.

Thanks for your help.
