### ISSUE TITLE
Installation Failure on Mac

### ISSUE THREAD

**Issue by tarlen5** [cpmech/gosl#3]
Hi,

I have tried to install this useful package on my system and I have run into an installation failure on my Mac OS X, running version 10.11.5. I believe I have gone through the appropriate installation steps 1-5, but then at step 6, when I run `./all.bash` from the `gosl/` directory that I cloned, I get the following error output (screenshot)
![screen shot 2016-09-29 at 9 04 04 am](https://cloud.githubusercontent.com/assets/6472638/18961971/b63f759e-8623-11e6-9742-da29ecad26a3.png)

Any ideas what could be going wrong or how to diagnose this?

Thanks,
Tim

**Comment by cpmech** [comment]
Hi, thanks for your interest in Gosl. The error above is not a problem actually. The unit test tries to check for the function name at runtime, but it only works on Linux. So, I have disabled the test. Please let us know if you find any other problem. Cheers. Dorival
