### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by systra72** [cpmech/gosl#40]
Hi! I'm new to go and I'm new to gosl. Trying to install it on MacOS following the instructions. When testing, it fails on the h5-tests: 

compiling io/h5 =============================================================
 github.com/cpmech/gosl/io/h5
Undefined symbols for architecture x86_64:
...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)  

How to fix that? I was ignoring this warning: 
Warning: hdf5 dependency gcc was built with a different C++ standard

Kind regards

**Comment by cpmech** [comment]
Hi there. I've tried to solve this issue but could not succeed yet. It seems that (my) installation on macOS is broken. For the moment, my advice is to disable h5 completely on macOS (we use it only for few tests)

**Comment by cpmech** [comment]
Hello again. We've spent time working on this and the "final" solution is to use Docker. So, we're working on updated documentation and code for Windows, Linux, and macOS, all using Docker. Thanks for your time again.
