### ISSUE TITLE
Thin plate splines

### ISSUE THREAD

**Issue by qmuntal** [cpmech/gosl#41]
I´m interested in moving some R scripts to Go, and I´m missing a way to generate Thin Plate Splines in a similar fashion as https://www.rdocumentation.org/packages/bigsplines/versions/1.1-1/topics/bigtps.

Is it possible to create something similar using `gosl`? If not, is the codebase prepared to smoothly implement it?

**Comment by cpmech** [comment]
Hi there. I suppose it's possible to implement in Gosl. However, this bigtps seems to rely on bigsplines which contains several functions. Therefore, it might be a major work to get all done.
