### ISSUE TITLE
mpi code location

### ISSUE THREAD

**Issue by sbromberger** [cpmech/gosl#58]
Hi gosl folks,

A while back I extracted the MPI code because I needed to do some work with it. I noticed you're no longer bundling it. Perhaps you might put a link to my repo somewhere in your README in case folks are still looking for it?

https://github.com/sbromberger/gompi is the repo. (Also, if you have any comments/suggestions on the code I'd be grateful!)

Thanks.

**Comment by cpmech** [comment]
Sure, I've mentioned your library as shown here https://github.com/cpmech/gosl/commit/1b5e268b1f16452b72e1eac57a3a459979e6e399

I've glanced over your code and it looks great!

Thanks.
Dorival

**Comment by sbromberger** [comment]
This is great. Many thanks!
