### ISSUE TITLE
Munkres doesn't return the best value

### ISSUE THREAD

**Issue by asdine** [cpmech/gosl#6]
For the following matrix we have an issue with the munkres implementation:
```go
matrix := [][]int{
	[]int{11757, 6957},
	[]int{28985, 24171},
	[]int{33857, 29057},
}
```

Expected result:
```go
 []int{0, -1, 1}
```

Actual result:
```go
[]int{1, 0, -1}
```

cc @christophe-dufour @Nyks06 @skateinmars

**Comment by cpmech** [comment]
Hi,

Thanks a lot for your interest in our code.

Can you please post a working code?

I've run here and got:
links = [0 1 -1]
cost = 35928

With links = [1, 0, -1], the cost would be higher: cost = 35942, right?

This i the code I've used:

`	
C := [][]float64{
	{11757, 6957},
	{28985, 24171},
	{33857, 29057},
}

var mnk Munkres
mnk.Init(len(C), len(C[0]))
mnk.SetCostMatrix(C)
mnk.Run()

io.Pforan("links = %v\n", mnk.Links)
io.Pforan("cost = %v\n", mnk.Cost)
`

**Comment by skateinmars** [comment]
Here is a complete working example:

```
package main

import (
	"fmt"

	"github.com/cpmech/gosl/graph"
)

func main() {
	matrixOK := [][]float64{
		[]float64{11757.0, 6957.0},
		[]float64{28985.0, 24171.0},
		[]float64{33857.0, 29057.0},
	}

	matrixNOK := [][]float64{
		[]float64{11757.0, 6957.0},
		[]float64{33857.0, 29057.0},
		[]float64{28985.0, 24171.0},
	}

	var mnk graph.Munkres
	mnk.Init(len(matrixOK), len(matrixOK[0]))
	mnk.SetCostMatrix(matrixOK)
	mnk.Run()

	fmt.Printf("links= %v\n", mnk.Links)
	fmt.Printf("cost= %v\n", mnk.Cost)

	var mnk2 graph.Munkres
	mnk2.Init(len(matrixNOK), len(matrixNOK[0]))
	mnk2.SetCostMatrix(matrixNOK)
	mnk2.Run()

	fmt.Printf("links= %v\n", mnk2.Links)
	fmt.Printf("cost= %v\n", mnk2.Cost)
}
```

The output is as follows:
```
links= [0 1 -1]
cost= 35928
links= [1 0 -1]
cost= 40814
```

As you can see, depending on the order of the matrix lines the result is different.

**Comment by cpmech** [comment]
Thanks a lot for finding this problem!

It happens with non-square matrices. Now, the cost matrix is padded with zeros (in this case).

It has been fixed as shown [here](https://github.com/cpmech/gosl/commit/73ccac38a17182ff4057e5d6b16d03abc0da1ef0)

See also the last test [here](https://github.com/cpmech/gosl/blob/master/graph/t_munkres_test.go)

Please feel free to let us know of any other issue!

Cheers.
Dorival
