### ISSUE TITLE
maybe a Bug

### ISSUE THREAD

**Issue by baofengqqwwff** [cpmech/gosl#8]
>>> compiling la <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
   platform = windows
   GOPATH = E:/GoProject
   GOSL = E:/GoProject/src/github.com/cpmech/gosl
# github.com/cpmech/gosl/la
E:/GoProject/src/github.com/cpmech/gosl/lib/libumfpack.a(umf_dl_local_search.o):                                                 umf_local_search.c:(.text+0x162c): undefined reference to `dtrsv_'
E:/GoProject/src/github.com/cpmech/gosl/lib/libumfpack.a(umf_zl_local_search.o):                                                 umf_local_search.c:(.text+0x13ae): undefined reference to `zgemv_'
E:/GoProject/src/github.com/cpmech/gosl/lib/libumfpack.a(umf_zl_local_search.o):                                                 umf_local_search.c:(.text+0x148a): undefined reference to `ztrsv_'
E:/GoProject/src/github.com/cpmech/gosl/lib/libumfpack.a(umf_zl_blas3_update.o):                                                 umf_blas3_update.c:(.text+0x649): undefined reference to `zgemm_'
E:/GoProject/src/github.com/cpmech/gosl/lib/libumfpack.a(umf_zl_blas3_update.o):                                                 umf_blas3_update.c:(.text+0x6ee): undefined reference to `ztrsm_'
E:/GoProject/src/github.com/cpmech/gosl/lib/libumfpack.a(umf_zl_blas3_update.o):                                                 umf_blas3_update.c:(.text+0x77b): undefined reference to `zgeru_'
collect2.exe: error: ld returned 1 exit status

**Comment by cpmech** [comment]
Hi, thanks for reporting the issue. Does the problem still persist?

**Comment by baofengqqwwff** [comment]
sorry i don't try any more,maybe latter
