### ISSUE TITLE
compiling la failed

### ISSUE THREAD

**Issue by battilanast** [cpmech/gosl#9]
Hi,
Was working through the steps as described in https://github.com/cpmech/gosl/blob/master/doc/InstallationOnMacOS.md and got literally stuck on the very last step. So, while trying to install the gosl package everything went well until gosl/la where I got this in my terminal:
>>> compiling la <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
signal: killed
FAIL	github.com/cpmech/gosl/la	0.005s

I was not able to find a solution on the net, so I hope to work out a solution with you guys, since my Bachelor Thesis program using Go should run as efficient as possible.

My macbook pro (early 2011) is running macOS Sierra (10.12.5) and has a Intel GPU, therefore no CUDA.

![terminal1](https://user-images.githubusercontent.com/29484151/27229123-938a2996-52aa-11e7-8c5c-d2b0134173ca.png)

**Comment by cpmech** [comment]
Hi,

Thanks for your interest on Gosl.

I have tested here again on my 2013 MacBookAir (macOS Sierra Version 10.12.5) with the latest MacPorts, latest SuiteSparse, and latest Golang (go version go1.8.3 darwin/amd64) and all seems fine.

Please note that we don't use CUDA, so not worries there.

I think that we could use the _dolfin_ from Macports to simplify the installation of SuiteSparse a little bit. I'll try this right now and then will update the macOS installation instructions.

Meanwhile, could you please uncomment the `//verbose()` command on line **107** of `t_linsol_test.go` and run `go test -test.run=linsol01a` from within the `la` directory to see if you get the following output?

```
================= linsol01a. real =================
x OK
max|r[i]| = 1.0658141036401503e-14 OK
PASS
ok  	github.com/cpmech/gosl/la	0.004s
```

Also, can you please let me know what `go version` you have?

Cheers.
Dorival

**Comment by cpmech** [comment]
Hi,

I've installed again from scratch but now using HomeBrew (https://brew.sh/).

Everything seems fine.

I've updated the installation instructions: https://github.com/cpmech/gosl/blob/master/doc/InstallationOnMacOS.md

Please let me know if you still have problems.

Cheers.
Dorival

**Comment by battilanast** [comment]
Hi,

Thanks for answering.

I have the following `go version`:
> go version go1.8.3 darwin/amd64

After uncommenting the suggested line 107 of `t_linsol_test.go` and running `go test -test.run=linsol01a` from within the `la` directory I got the following result:
>   Referenced from: /Users/battilanast/pkg/SuiteSparse/lib/libumfpack.5.7.6.dylib
>   Reason: image not found
> signal: abort trap
> FAIL	github.com/cpmech/gosl/la	0.006s

I had a look on the new installation instructions and followed them as well. Now I received the following error:
> \>>> compiling la <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
> dyld: Library not loaded: @rpath/libiomp5.dylib
>   Referenced from: /Users/battilanast/pkg/SuiteSparse/lib/libumfpack.5.7.6.dylib
>   Reason: image not found
> signal: abort trap
> FAIL	github.com/cpmech/gosl/la	0.009s

What exactly do you mean when you says you installed from scratch? Did you just remove the goal directory?

Best
Steven

**Comment by cpmech** [comment]
I mean that I've removed all software and installed everything again, including removing mac ports (https://guide.macports.org/chunked/installing.macports.uninstalling.html) and cloning the Gosl repository again.

Now, the problem with the **image not found** is somewhat outside my knowledge. I never had this problem with my Mac (but I don't use it very much...)

Can you please see if the Mac community may have an answer?

**Comment by cpmech** [comment]
You may also try changing the `-L/usr/local/lib` at line number 21 in the gosl/la/flags.go file.

I'll try this again in my Mac tomorrow...

**Comment by cpmech** [comment]
Hi Steven,

I've just checked again in my macOS and all seems fine (deleted everything and installed again).

I think the problem may be some old compiled libraries in your $GOPATH/pkg directory.

Also, please note:
1. When using Homebrew (highly recommended over Macports), we don't need to compile SuiteSparse any longer! So, we should not see a linkage to "/Users/.../pkg/SuiteSparse/..."! In fact, we don't need the "pkg" directory.
2. A previous compilation of Gosl with ./all.bash may have left some binaries in your $GOPATH/pkg/darwin_amd64/github.com/cpmech. So, please delete this directory (or all *.a files in there)

I hope it will work!
Cheers.
Dorival

**Comment by battilanast** [comment]
Hi Dorival,

Thank you.
I tried it again today and it is still not working because I am still getting the image not found error but am currently trying to find a solution in the Mac community. If that does not help I will try to find another mac and see if it works there.

Best,
Steven

**Comment by cpmech** [comment]
Sure; I'm happy to help too.

Also, please note that you shouldn't have _ /Users/battilanast/pkg/SuiteSparse/lib/libumfpack.5.7.6.dylib_ any longer

**Comment by battilanast** [comment]
yes, it is not there anymore, the error message looks like this now:
> \>>> compiling la <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
dyld: Library not loaded: @rpath/libiomp5.dylib
  Referenced from: /usr/local/lib/libumfpack.5.7.6.dylib
  Reason: image not found
signal: abort trap
FAIL	github.com/cpmech/gosl/la	0.010s

**Comment by cpmech** [comment]
ok; I've tried everything here but am puzzled as well.

I've read many web pages about the problem as well. Some people recommend adding an environment variable named DYLD_LIBRARY_PATH (in your case pointing to /usr/local/lib). But I don't have this variable in my system (never had) and it always worked. So strange...

There are some information on Intel's website: https://software.intel.com/en-us/articles/dyld-library-not-loadedlibiomp5dylib

**Comment by cpmech** [comment]
This page may shed some light too: http://droolfactory.blogspot.com.au/2012/07/fixing-dyld-image-not-found-on-mac-os.html

**Comment by battilanast** [comment]
It is still not working but I was able to install it on another mac. Will just use this for my task.
Thanks a lot for the support.

Best,
Steven

**Comment by cpmech** [comment]
So, it's working on the other Mac, right?

**Comment by battilanast** [comment]
Yes, it seems to work perfectly fine on the other Mac.

**Comment by cpmech** [comment]
All right. I'll close this ticket now but if I encounter the solution to this problem, I'll update here. Also, please feel free to re-open the issue whenever you like. Best wishes. Dorival
